.PHONY: clean All

All:
	@echo "----------Building project:[ ExplicitTypeCast - Debug ]----------"
	@cd "ExplicitTypeCast" && "$(MAKE)" -f  "ExplicitTypeCast.mk"
clean:
	@echo "----------Cleaning project:[ ExplicitTypeCast - Debug ]----------"
	@cd "ExplicitTypeCast" && "$(MAKE)" -f  "ExplicitTypeCast.mk" clean
