.PHONY: clean All

All:
	@echo "----------Building project:[ CppStringsFunct - Debug ]----------"
	@cd "CppStringsFunct" && "$(MAKE)" -f  "CppStringsFunct.mk"
clean:
	@echo "----------Cleaning project:[ CppStringsFunct - Debug ]----------"
	@cd "CppStringsFunct" && "$(MAKE)" -f  "CppStringsFunct.mk" clean
