.PHONY: clean All

All:
	@echo "----------Building project:[ Quiz - Debug ]----------"
	@cd "Quiz" && "$(MAKE)" -f  "Quiz.mk"
clean:
	@echo "----------Cleaning project:[ Quiz - Debug ]----------"
	@cd "Quiz" && "$(MAKE)" -f  "Quiz.mk" clean
